const dummyevents = [
  {
    id: 1,
    img: `https://images.pexels.com/photos/919734/pexels-photo-919734.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr`,
    title: "Investment in Real Story v/s Real Estate - Meet and Greet",
    host: "Hosted By: Nishant",
    time: "27 Feb,2024",
    state: "Delhi",
    price: "₹999",
  },
  {
    id: 2,
    img: `https://images.pexels.com/photos/1157557/pexels-photo-1157557.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr`,
    title: "Holi Celebration - Private Farmhouse",
    host: "Hosted By: Mahaprasad",
    time: "22 March,2024",
    state: "Delhi",
    price: "₹499",
  },
  {
    id: 3,
    img: `https://images.pexels.com/photos/1566754/pexels-photo-1566754.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr`,
    title: "Annual Cyclathon Event Powered By Atlas ",
    host: "Hosted By: AtlasInfo",
    time: "25 April,2024",
    price: "₹599",
  },
  {
    id: 4,
    img: `https://images.pexels.com/photos/15241077/pexels-photo-15241077/free-photo-of-volkswagen-beetle-cars-on-parking-lot.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr`,
    title: "Weekly AutoMobile Expo",
    host: "Hosted By: Tata&Industires",
    time: "3 March,2024",
    price: "₹ FREE",
  },
  {
    id: 5,
    img: `https://images.pexels.com/photos/15241077/pexels-photo-15241077/free-photo-of-volkswagen-beetle-cars-on-parking-lot.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr`,
    title: "Weekly AutoMobile Expo",
    host: "Hosted By: Tata&Industires",
    time: "3 March,2024",
    price: "₹ FREE",
  },
  {
    id: 6,
    img: `https://images.pexels.com/photos/15241077/pexels-photo-15241077/free-photo-of-volkswagen-beetle-cars-on-parking-lot.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr`,
    title: "Weekly AutoMobile Expo",
    host: "Hosted By: Tata&Industires",
    time: "3 March,2024",
    price: "₹ FREE",
  },
  {
    id: 7,
    img: `https://images.pexels.com/photos/15241077/pexels-photo-15241077/free-photo-of-volkswagen-beetle-cars-on-parking-lot.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr`,
    title: "Weekly AutoMobile Expo",
    host: "Hosted By: Tata&Industires",
    time: "3 March,2024",
    price: "₹ FREE",
  },
  {
    id: 8,
    img: `https://images.pexels.com/photos/15241077/pexels-photo-15241077/free-photo-of-volkswagen-beetle-cars-on-parking-lot.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr`,
    title: "Weekly AutoMobile Expo",
    host: "Hosted By: Tata&Industires",
    time: "3 March,2024",
    price: "₹ FREE",
  },
];

export default dummyevents;
